-- ============================================================================
-- hrcd-rekap : 0063_sekolah_daftar_kurasi.sql
-- Isi tabel `sekolah` dengan daftar kurasi.
--
-- APA INI
--
-- 188 sekolah, dirakit dari empat lembar pendaftaran edisi XXXIII-XXXVI:
-- 1.102 baris peserta, 326 tulisan tangan, digabung jadi klaster lalu dilacak
-- satu per satu ke Data Referensi Kemendikdasmen. Prosesnya, beserta setiap
-- jebakan yang ditemukan di jalan, ada di `docs/runbook-sekolah.md`.
--
-- Sebarannya:
--
--   Kabupaten Ciamis             102
--   Kabupaten Indramayu           15
--   Kota Banjar                   14
--   Kota Tasikmalaya               8
--   Kabupaten Kuningan             7
--   Kabupaten Tasikmalaya          7
--   Kabupaten Majalengka           6
--   Kabupaten Pangandaran          5
--
-- KENAPA DIPASANG SEKARANG, BUKAN DIBIARKAN TUMBUH SENDIRI
--
-- Tanpa ini, tabel `sekolah` terisi dari apa yang diketik pembina di kotak
-- "Asal sekolah" — dan itulah yang melahirkan 36 baris untuk 23 sekolah
-- sebelum 0061. Pagar di 0061 mencegahnya BERLIPAT, tapi tidak membuat baris
-- pertamanya benar: sekolah yang belum ada tetap lahir dari tulisan tangan,
-- lengkap dengan alamat `nan` dan `Jl` tanpa titik.
--
-- Dengan daftar ini terpasang, pembina hampir selalu MEMILIH, bukan mengetik.
-- Itu satu ketukan di HP, bukan satu paragraf alamat — dan alamat yang
-- tersimpan sudah benar sejak baris pertamanya.
--
-- YANG SENGAJA TIDAK IKUT
--
-- - **SMK Nusantara 1 Bekasi** — TIDAK KETEMU, dan kali ini dicari dari sisi ALAMAT, bukan dari nama
-- - **SMPN 1 Kalijaya** — DITAHAN - kandidatnya kuat tapi namanya tidak cocok, jadi sengaja tidak diisikan
--
-- Keduanya sudah disisir dari sisi alamat, bukan cuma dari sisi nama, dan
-- buntu. Memasang tebakan lebih buruk daripada tidak memasang apa-apa:
-- pembina yang tidak menemukan sekolahnya akan mengetiknya sendiri, dan itu
-- jalan yang memang disediakan. Yang menemukan sekolah dengan alamat SALAH
-- tidak akan curiga sama sekali.
--
-- 19 baris berkeyakinan `sedang` IKUT dipasang. Yang `sedang` di sana hampir
-- selalu kode posnya, bukan sekolahnya — nama dan alamat jalannya sudah dari
-- Data Referensi, dan yang berselisih cuma lima angka terakhir antar sumber.
-- Menahan sekolah yang namanya sudah pasti karena satu digit kode pos akan
-- memaksa pembinanya mengetik ulang seluruh alamatnya dari nol, yang justru
-- lebih mungkin salah.
--
-- BISA DIJALANKAN ULANG
--
-- `on conflict do update`, jadi menjalankannya dua kali tidak melahirkan
-- baris kedua — ia hanya menimpa nama dan alamatnya dengan yang sama.
-- Pendaftaran yang sudah menunjuk baris itu tidak tersentuh, karena `id`-nya
-- tidak berubah.
-- ============================================================================

drop table if exists sekolah_kurasi;
create temporary table sekolah_kurasi (nama text, alamat text);
insert into sekolah_kurasi (nama, alamat) values
  ('MA Agrowisata Shaleha',
   'Jl. Sriwinangun No. 01, Panjalu, Kec. Panjalu, Kabupaten Ciamis, Jawa Barat 46264, Indonesia'),
  ('MA Al-Azhar Kota Banjar',
   'Jl. Pesantren No. 02, Kujangsari, Kec. Langensari, Kota Banjar, Jawa Barat 46345, Indonesia'),
  ('MA Al-Hasan',
   'Karangampel, Kec. Baregbeg, Kabupaten Ciamis, Jawa Barat 46274, Indonesia'),
  ('MA Al-Ishlah',
   'Jl. Raya Panjalu No. 02, Cihaurbeuti, Kec. Cihaurbeuti, Kabupaten Ciamis, Jawa Barat 46262, Indonesia'),
  ('MA Al-Kautsar',
   'Jl. Pejuang No. 100, Jajawar, Kec. Banjar, Kota Banjar, Jawa Barat 46318, Indonesia'),
  ('MA Al-Ma''sum Malausma',
   'Jl. Desa Malausma - Bungursari, Malausma, Kec. Malausma, Kabupaten Majalengka, Jawa Barat, Indonesia'),
  ('MA Assalimiyah',
   'Jl. KH. Salim No. 1, Darmacaang, Kec. Cikoneng, Kabupaten Ciamis, Jawa Barat 46261, Indonesia'),
  ('MA BKMU Cikijing',
   'Jl. Cirawa No. 01, Cikijing, Kec. Cikijing, Kabupaten Majalengka, Jawa Barat 45466, Indonesia'),
  ('MA Darul Huda',
   'Jl. Sadananya, Lingkungan Karangsari RT 02 RW 10, Maleber, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46214, Indonesia'),
  ('MA El-Bas',
   'Jl. Angganaya No. 37, Imbanagara, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46219, Indonesia'),
  ('MA Ibadul Ghafur',
   'Jl. Tanjungsukur No. 1A, Tanjungsukur, Kec. Rajadesa, Kabupaten Ciamis, Jawa Barat 46254, Indonesia'),
  ('MA Nurul Huda',
   'Jl. Kawali - Panjalu No. 123, Kawali, Kec. Kawali, Kabupaten Ciamis, Jawa Barat 46253, Indonesia'),
  ('MA PERSIS Sindangkasih',
   'Jl. Raya Ancol No. 27, Sindangkasih, Kec. Sindangkasih, Kabupaten Ciamis, Jawa Barat 46268, Indonesia'),
  ('MA PUI Cijantung',
   'Jl. Raya Banjar Km. 3 No. 141, Dewasari, Kec. Cijeungjing, Kabupaten Ciamis, Jawa Barat 46271, Indonesia'),
  ('MA Terpadu Ar-Rahman',
   'Jl. Arrahman No. 01, Nasol, Kec. Cikoneng, Kabupaten Ciamis, Jawa Barat 46261, Indonesia'),
  ('MA YPI Rijalul Hikam',
   'Jl. Raya Jatinagara No. 03, Jatinagara, Kec. Jatinagara, Kabupaten Ciamis, Jawa Barat 46273, Indonesia'),
  ('MAN 1 Kota Tasikmalaya',
   'Jl. Awipari 1, Awipari, Kec. Cibeureum, Kota Tasikmalaya, Jawa Barat, Indonesia'),
  ('MAN 1 Kuningan',
   'Jl. Mayasih No. 881, Cigugur, Kec. Cigugur, Kabupaten Kuningan, Jawa Barat 45552, Indonesia'),
  ('MAN 1 Sukabumi',
   'Jl. Suryakencana Km. 2, Pamuruyan, Kec. Cibadak, Kabupaten Sukabumi, Jawa Barat 43351, Indonesia'),
  ('MAN 2 Ciamis',
   'Jl. Yos Sudarso No. 53, Ciamis, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46211, Indonesia'),
  ('MAN 3 Ciamis',
   'Jl. K.H. Moch. Sirodj, Dewasari, Kec. Cijeungjing, Kabupaten Ciamis, Jawa Barat 46271, Indonesia'),
  ('MAN 3 Tasikmalaya',
   'Jl. Raya Panumbangan No. 33, Pakemitan, Kec. Ciawi, Kabupaten Tasikmalaya, Jawa Barat 46456, Indonesia'),
  ('MAN 4 Bantul Yogyakarta',
   'Jl. Ring Road Timur Pranti, Banguntapan, Kec. Banguntapan, Kabupaten Bantul, DI Yogyakarta 55198, Indonesia'),
  ('MAN 4 Jakarta',
   'Jl. Ciputat Raya, Pondok Pinang, Kec. Kebayoran Lama, Kota Administrasi Jakarta Selatan, DKI Jakarta 12310, Indonesia'),
  ('MAN 5 Ciamis',
   'Jl. Sukajadi No. 04, Maparah, Kec. Panjalu, Kabupaten Ciamis, Jawa Barat 46264, Indonesia'),
  ('MAN 6 Ciamis',
   'Jl. Rumah Sakit No. 20, Situmandala, Kec. Rancah, Kabupaten Ciamis, Jawa Barat, Indonesia'),
  ('MAN 6 Tasikmalaya',
   'Jl. Pemuda I, Hegarwangi, Kec. Bantarkalong, Kabupaten Tasikmalaya, Jawa Barat 46487, Indonesia'),
  ('MAN Darussalam',
   'Jl. K.H. Ahmad Fadlil II No. 53, Dewasari, Kec. Cijeungjing, Kabupaten Ciamis, Jawa Barat 46271, Indonesia'),
  ('MTs Al-Fadliliyah Darussalam',
   'Jl. K.H. Ahmad Fadlil I, Dewasari, Kec. Cijeungjing, Kabupaten Ciamis, Jawa Barat 46271, Indonesia'),
  ('MTs Al-Hasan Banjarsari',
   'Jl. Kawasen No. 80, Kawasen, Kec. Banjarsari, Kabupaten Ciamis, Jawa Barat 46383, Indonesia'),
  ('MTs Al-Huda Sadananya',
   'Dusun Tonggoh RT 02 RW 01, Sadananya, Kec. Sadananya, Kabupaten Ciamis, Jawa Barat 46256, Indonesia'),
  ('MTs Al-Iqna Cisaga',
   'Jl. Cimanggu No. 09 RT 01 RW 08, Cisaga, Kec. Cisaga, Kabupaten Ciamis, Jawa Barat, Indonesia'),
  ('MTs Al-Istiqomah Kiarapayung',
   'Jl. Rancah-Ciilat No. 131, Kiarapayung, Kec. Rancah, Kabupaten Ciamis, Jawa Barat, Indonesia'),
  ('MTs Ar-Rahman',
   'Jl. Arrahman No. 2, Nasol, Kec. Cikoneng, Kabupaten Ciamis, Jawa Barat 46261, Indonesia'),
  ('MTs Assalamiyah',
   'Jl. KH. Salim No. 1, Darmacaang, Kec. Cikoneng, Kabupaten Ciamis, Jawa Barat 46261, Indonesia'),
  ('MTs At-Tabiyah',
   'Jl. Desa Gunungsari RT 06 RW 02, Gunungsari, Kec. Sadananya, Kabupaten Ciamis, Jawa Barat 46256, Indonesia'),
  ('MTs El-Bas',
   'Jl. Angganaya No. 37, Imbanagara Raya, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46219, Indonesia'),
  ('MTs Harapan Baru',
   'Jl. Raya Banjar KM 03, Cijeungjing, Kec. Cijeungjing, Kabupaten Ciamis, Jawa Barat 46271, Indonesia'),
  ('MTs PUI Cijantung',
   'Jl. Raya Banjar Km. 3 No. 141, Dusun Bojongsari RT 08 RW 04, Dewasari, Kec. Cijeungjing, Kabupaten Ciamis, Jawa Barat 46271, Indonesia'),
  ('MTs Rancah',
   'Jl. Cibeureum No. 50, Rancah, Kec. Rancah, Kabupaten Ciamis, Jawa Barat, Indonesia'),
  ('MTs Rijalul Hikam',
   'Jl. Raya Jatinagara No. 03, Jatinagara, Kec. Jatinagara, Kabupaten Ciamis, Jawa Barat 46273, Indonesia'),
  ('MTs Rijalul Ulum',
   'Dusun Kalapanunggal RT 30 RW 12, Sindangsari, Kec. Cikoneng, Kabupaten Ciamis, Jawa Barat 46261, Indonesia'),
  ('MTs Serba Bakti Suryalaya',
   'Jl. Raya Suryalaya, Tanjungkerta, Kec. Pagerageung, Kabupaten Tasikmalaya, Jawa Barat 46158, Indonesia'),
  ('MTsN 2 Banjar',
   'Jl. Pengairan Pondok Huni No. 156, Bojongkantong, Kec. Langensari, Kota Banjar, Jawa Barat 46346, Indonesia'),
  ('MTsN 2 Ciamis',
   'Jl. Panjalu-Babantar No. 308, Awiluar, Kec. Lumbung, Kabupaten Ciamis, Jawa Barat 46258, Indonesia'),
  ('MTsN 5 Ciamis',
   'Dusun Mandalagiri RT 03 RW 03, Cisontrol, Kec. Rancah, Kabupaten Ciamis, Jawa Barat, Indonesia'),
  ('MTsN 9 Tasikmalaya',
   'Jl. Raya Pamijahan, Pamijahan, Kec. Bantarkalong, Kabupaten Tasikmalaya, Jawa Barat 46487, Indonesia'),
  ('MTsN Rajadesa',
   'Jl. Cipancur No. 6, Sirnabaya, Kec. Rajadesa, Kabupaten Ciamis, Jawa Barat 46254, Indonesia'),
  ('SMA 1 Sindangkasih',
   'Jl. Raya Sindangkasih Cikoneng, Sindangkasih, Kec. Sindangkasih, Kabupaten Ciamis, Jawa Barat 46268, Indonesia'),
  ('SMA Al Hasan Banjarsari',
   'Jl. Kawasen No. 80, Kawasen, Kec. Banjarsari, Kabupaten Ciamis, Jawa Barat 46383, Indonesia'),
  ('SMA Al Irsyad Al Islamiyyah',
   'Jl. Prof. Dr. Suharso, Arcawinangun, Kec. Purwokerto Timur, Kabupaten Banyumas, Jawa Tengah 53113, Indonesia'),
  ('SMA Al-Muttaqin',
   'Jl. A. Yani No. 140, Sukamanah, Kec. Cipedes, Kota Tasikmalaya, Jawa Barat 46131, Indonesia'),
  ('SMA Binaul Ummah',
   'Jl. Raya Cipari, Cipari, Kec. Cigugur, Kabupaten Kuningan, Jawa Barat 45552, Indonesia'),
  ('SMA IT Al-Falah',
   'Jl. Citalahab, Mekarjaya, Kec. Bungbulang, Kabupaten Garut, Jawa Barat 44165, Indonesia'),
  ('SMA Informatika Ciamis',
   'Jl. Bojonghuni No. 9, Maleber, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46214, Indonesia'),
  ('SMA Islam Ainurrafiq',
   'Jl. Pemuda No. 001, Panawuan, Kec. Cigandamekar, Kabupaten Kuningan, Jawa Barat 45556, Indonesia'),
  ('SMA Islam Nurul Fikri',
   'Jl. Palka, Bantarwaru, Kec. Cinangka, Kabupaten Serang, Banten 42167, Indonesia'),
  ('SMA Kesatrian 1 Semarang',
   'Jl. Pamularsih No. 116, Gisikdrono, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50149, Indonesia'),
  ('SMA Plus Assyfa',
   'Jl. Raya Subang-Bandung KM 12, Tambakmekar, Kec. Jalancagak, Kabupaten Subang, Jawa Barat 41281, Indonesia'),
  ('SMA Plus Darussalam',
   'Jl. K.H. Ahmad Fadlil No. 2, Dewasari, Kec. Cijeungjing, Kabupaten Ciamis, Jawa Barat 46271, Indonesia'),
  ('SMA Plus Ibnu Sina',
   'Jl. Cikampak - Segog KM 9, Cibening, Kec. Pamijahan, Kabupaten Bogor, Jawa Barat 16698, Indonesia'),
  ('SMA Terpadu Ar-Risalah',
   'Jl. Raya Banjar KM 3,5, Pamalayan, Kec. Cijeungjing, Kabupaten Ciamis, Jawa Barat 46271, Indonesia'),
  ('SMA Terpadu Cikanyere',
   'Dusun Cigoong RT 01 RW 01, Sirnabaya, Kec. Rajadesa, Kabupaten Ciamis, Jawa Barat 46254, Indonesia'),
  ('SMA Terpadu Dampasan',
   'Jl. Pasir Garu, Dusun Tuban RT. 002/RW. 006, Ratawangi, Kec. Banjarsari, Kabupaten Ciamis, Jawa Barat 46383, Indonesia'),
  ('SMA Terpadu Riyadlul Ulum',
   'Komplek Pesantren Condong-Cibeurem, Setianagara, Kec. Cibeureum, Kota Tasikmalaya, Jawa Barat 46196, Indonesia'),
  ('SMA YRM Cihawar',
   'Jl. Raya Cihawar No. 151, Sukaharja, Kec. Rajadesa, Kabupaten Ciamis, Jawa Barat 46254, Indonesia'),
  ('SMA Yadika Sumedang',
   'Jl. Raya Tanjungsari No. 394 A, Gudang, Kec. Tanjungsari, Kabupaten Sumedang, Jawa Barat 45362, Indonesia'),
  ('SMAN 1 Banjar',
   'Jl. K.H. Mustofa No. 1, Banjar, Kec. Banjar, Kota Banjar, Jawa Barat 46311, Indonesia'),
  ('SMAN 1 Banjarsari',
   'Jl. Raya KM 03 Banjarsari, Ratawangi, Kec. Banjarsari, Kabupaten Ciamis, Jawa Barat 46383, Indonesia'),
  ('SMAN 1 Baregbeg',
   'Jl. R.E. Martadinata No. 150, Baregbeg, Kec. Baregbeg, Kabupaten Ciamis, Jawa Barat 46274, Indonesia'),
  ('SMAN 1 Cantigi',
   'Jl. Raya Panyingkiran Kidul, Panyingkiran Kidul, Kec. Cantigi, Kabupaten Indramayu, Jawa Barat 45251, Indonesia'),
  ('SMAN 1 Ciamis',
   'Jl. Gunung Galuh No. 37, Ciamis, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46211, Indonesia'),
  ('SMAN 1 Cihaurbeuti',
   'Jl. Kartawijaya No. 600, Pamokolan, Kec. Cihaurbeuti, Kabupaten Ciamis, Jawa Barat 46262, Indonesia'),
  ('SMAN 1 Cimaragas',
   'Jl. Raya Cimaragas No. 139 B, Cimaragas, Kec. Cimaragas, Kabupaten Ciamis, Jawa Barat 46381, Indonesia'),
  ('SMAN 1 Cineam',
   'Jl. Raya Cineam KM 0,13, Madiasari, Kec. Cineam, Kabupaten Tasikmalaya, Jawa Barat 46198, Indonesia'),
  ('SMAN 1 Cirebon',
   'Jl. Wahidin Sudirohusodo No. 81, Sukapura, Kec. Kejaksan, Kota Cirebon, Jawa Barat 45122, Indonesia'),
  ('SMAN 1 Cisaga',
   'Jl. Raya Cisaga-Ciamis No. 814, Mekarmukti, Kec. Cisaga, Kabupaten Ciamis, Jawa Barat 46386, Indonesia'),
  ('SMAN 1 Kandanghaur',
   'Jl. Raya Kandanghaur No. 286, Wirapanjunan, Kec. Kandanghaur, Kabupaten Indramayu, Jawa Barat 45254, Indonesia'),
  ('SMAN 1 Kawali',
   'Jl. Poronggol Raya No. 9, Kawalimukti, Kec. Kawali, Kabupaten Ciamis, Jawa Barat 46253, Indonesia'),
  ('SMAN 1 Larangan',
   'Jl. Raya Barat Sitanggal Larangan, Sitanggal, Kec. Larangan, Kabupaten Brebes, Jawa Tengah 52262, Indonesia'),
  ('SMAN 1 Lohbener',
   'Jl. Raya Utara Lohbener, Lohbener, Kec. Lohbener, Kabupaten Indramayu, Jawa Barat 45252, Indonesia'),
  ('SMAN 1 Maja',
   'Jl. Raya Maja Selatan No. 6, Maja Selatan, Kec. Maja, Kabupaten Majalengka, Jawa Barat 45461, Indonesia'),
  ('SMAN 1 Majenang',
   'Jl. Raya Pahonjean, Cibeunying, Kec. Majenang, Kabupaten Cilacap, Jawa Tengah 53257, Indonesia'),
  ('SMAN 1 Mangunjaya',
   'Jl. Raya Mangunjaya, Mangunjaya, Kec. Mangunjaya, Kabupaten Pangandaran, Jawa Barat 46371, Indonesia'),
  ('SMAN 1 Pamanukan',
   'Jl. Eyang Tirtapraja No. 83, Pamanukan, Kec. Pamanukan, Kabupaten Subang, Jawa Barat 41254, Indonesia'),
  ('SMAN 1 Pamarican',
   'Jl. Pamarican No. 44, Neglasari, Kec. Pamarican, Kabupaten Ciamis, Jawa Barat 46382, Indonesia'),
  ('SMAN 1 Panawangan',
   'Jl. Raya Ciamis-Cirebon Km. 159, Cinyasag, Kec. Panawangan, Kabupaten Ciamis, Jawa Barat 46255, Indonesia'),
  ('SMAN 1 Parigi',
   'Jl. Babakan Ardiyasa No. 62, Karangjaladri, Kec. Parigi, Kabupaten Pangandaran, Jawa Barat 46393, Indonesia'),
  ('SMAN 1 Rancah',
   'Jl. Raya Cisaga-Rancah KM. 2, Rancah, Kec. Rancah, Kabupaten Ciamis, Jawa Barat 46387, Indonesia'),
  ('SMAN 1 Sukadana',
   'Jl. Gardu Ciilat, Margaharja, Kec. Sukadana, Kabupaten Ciamis, Jawa Barat 46272, Indonesia'),
  ('SMAN 18 Garut',
   'Jl. Perum Bumi Abdi Negara 1, Sindanggalih, Kec. Karangpawitan, Kabupaten Garut, Jawa Barat 44182, Indonesia'),
  ('SMAN 2 Banjarsari',
   'Jl. Sukadana No. 239, Cigayam, Kec. Banjaranyar, Kabupaten Ciamis, Jawa Barat 46383, Indonesia'),
  ('SMAN 2 Ciamis',
   'Jl. K.H. Ahmad Dahlan No. 2, Linggasari, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46216, Indonesia'),
  ('SMAN 3 Banjar',
   'Jl. K.H. Mustofa No. 117, Banjar, Kec. Banjar, Kota Banjar, Jawa Barat 46311, Indonesia'),
  ('SMAN 3 Ciamis',
   'Jl. Bojonghuni No. 87, Maleber, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46214, Indonesia'),
  ('SMAN 6 Depok',
   'Jl. Limo Raya No. 30, Limo, Kec. Limo, Kota Depok, Jawa Barat 16515, Indonesia'),
  ('SMAN 9 Tasikmalaya',
   'Jl. Leuwidahu No. 61, Panyingkiran, Kec. Indihiang, Kota Tasikmalaya, Jawa Barat 46151, Indonesia'),
  ('SMK Adi Sanggoro',
   'Jl. Sengked No. 1, Babakan, Kec. Dramaga, Kabupaten Bogor, Jawa Barat 16680, Indonesia'),
  ('SMK Al Ihsan Pamarican',
   'Jl. Raya Pamarican - Kertahayu KM 1, Sukahurip, Kec. Pamarican, Kabupaten Ciamis, Jawa Barat 46382, Indonesia'),
  ('SMK Al-Istiqomah Rancah',
   'Jl. Rancah Ciilat No. 131, Kiarapayung, Kec. Rancah, Kabupaten Ciamis, Jawa Barat 46387, Indonesia'),
  ('SMK Bangkit Indonesia Talaga',
   'Jl. Ganeas No. 01, Ganeas, Kec. Talaga, Kabupaten Majalengka, Jawa Barat 45463, Indonesia'),
  ('SMK Bhakti Kencana Banjar',
   'Jl. Dr. Husein Kartasasmita No. 2, Banjar, Kec. Banjar, Kota Banjar, Jawa Barat 46311, Indonesia'),
  ('SMK Bhakti Kencana Ciamis',
   'Jl. Jend. Sudirman No. 283, Sindangrasa, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46215, Indonesia'),
  ('SMK Bina Putera Nusantara Tasikmalaya',
   'Jl. Sukarindik No. 63A, Panyingkiran, Kec. Indihiang, Kota Tasikmalaya, Jawa Barat 46151, Indonesia'),
  ('SMK Darul Ilmi Panawangan',
   'Jl. Ciamis-Cirebon No. 377, Sadapaingan, Kec. Panawangan, Kabupaten Ciamis, Jawa Barat 46255, Indonesia'),
  ('SMK Galuh Rahayu',
   'Jl. Raya Sukaraja, Sukaraja, Kec. Sindangkasih, Kabupaten Ciamis, Jawa Barat 46268, Indonesia'),
  ('SMK Informatika Citra Bangsa Panawangan',
   'Jl. Raya Ciamis - Cirebon KM 39, Gardujaya, Kec. Panawangan, Kabupaten Ciamis, Jawa Barat 46255, Indonesia'),
  ('SMK Karya Nasional Sindangkasih',
   'Jl. Raya Sindangkasih / Rajapolah, Gunungcupu, Kec. Sindangkasih, Kabupaten Ciamis, Jawa Barat 46268, Indonesia'),
  ('SMK Kehutanan Negeri Kadipaten',
   'Jl. Raya Timur Sawala, Cipaku, Kec. Kadipaten, Kabupaten Majalengka, Jawa Barat 45452, Indonesia'),
  ('SMK Ma''arif NU Ciamis',
   'Jl. Panamun No. 92, Sukamaju, Kec. Baregbeg, Kabupaten Ciamis, Jawa Barat 46274, Indonesia'),
  ('SMK Maarif Sabilunnajat Rancah',
   'Jl. Rancah - Karangpari, Cileungsir, Kec. Rancah, Kabupaten Ciamis, Jawa Barat 46387, Indonesia'),
  ('SMK Miftahussalam',
   'Jl. H. Ubad No. 94, Handapherang, Kec. Cijeungjing, Kabupaten Ciamis, Jawa Barat 46271, Indonesia'),
  ('SMK PGRI Cikoneng',
   'Jl. Raya Cikoneng-Ciamis No. 144, Cikoneng, Kec. Cikoneng, Kabupaten Ciamis, Jawa Barat 46261, Indonesia'),
  ('SMK PGRI Jatibarang',
   'Jl. Mayor Dasuki No. 159, Kebulen, Kec. Jatibarang, Kabupaten Indramayu, Jawa Barat 45273, Indonesia'),
  ('SMK Siliwangi AMS Banjarsari',
   'Jl. Raya Timur No. 60, Cibadak, Kec. Banjarsari, Kabupaten Ciamis, Jawa Barat, Indonesia'),
  ('SMK Taruna Indramayu',
   'Jl. Raya By Pass, Tambi Lor, Kec. Sliyeg, Kabupaten Indramayu, Jawa Barat 45281, Indonesia'),
  ('SMK Telematika Indramayu',
   'Jl. Raya Sindangkerta, Lohbener, Kec. Lohbener, Kabupaten Indramayu, Jawa Barat 45252, Indonesia'),
  ('SMK Terpadu Al Hasan Ciamis',
   'Jl. Puspa Lubis, Kertasari, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46213, Indonesia'),
  ('SMK YAPIIM Indramayu',
   'Jl. Kapuan Jaya No. 175, Dukuh, Kec. Indramayu, Kabupaten Indramayu, Jawa Barat 45215, Indonesia'),
  ('SMKN 1 Banjar',
   'Jl. K.H. Mustopa, Lingk. Parung Lesang RT 05 RW 10, Banjar, Kec. Banjar, Kota Banjar, Jawa Barat 46311, Indonesia'),
  ('SMKN 1 Binangun Kabupaten Cilacap',
   'Jl. Lapangan, Jati, Kec. Binangun, Kabupaten Cilacap, Jawa Tengah 53281, Indonesia'),
  ('SMKN 1 Ciamis',
   'Jl. Jenderal Sudirman No. 269, Sindangrasa, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46215, Indonesia'),
  ('SMKN 1 Cijulang',
   'Jl. Mayor Raswian, Kondangjajar, Kec. Cijulang, Kabupaten Pangandaran, Jawa Barat 46394, Indonesia'),
  ('SMKN 1 Cipaku',
   'Jl. Raya Kawali Km. 7, Muktisari, Kec. Cipaku, Kabupaten Ciamis, Jawa Barat 46252, Indonesia'),
  ('SMKN 1 Gabuswetan',
   'Jl. PU Rancahan, Rancahan, Kec. Gabuswetan, Kabupaten Indramayu, Jawa Barat 45263, Indonesia'),
  ('SMKN 1 Japara',
   'Jl. Raya Puskesmas, Japara, Kec. Japara, Kabupaten Kuningan, Jawa Barat 45555, Indonesia'),
  ('SMKN 1 Kawali',
   'Jl. Talagasari No. 35, Kawalimukti, Kec. Kawali, Kabupaten Ciamis, Jawa Barat 46253, Indonesia'),
  ('SMKN 1 Lemahabang',
   'Jl. K.H. Wahid Hasyim No. 76, Cipeujeuh Wetan, Kec. Lemahabang, Kabupaten Cirebon, Jawa Barat 45183, Indonesia'),
  ('SMKN 1 Losarang',
   'Jl. Raya Santing, Santing, Kec. Losarang, Kabupaten Indramayu, Jawa Barat 45253, Indonesia'),
  ('SMKN 1 Malausma',
   'Jl. Kartabraja No. 01, Malausma, Kec. Malausma, Kabupaten Majalengka, Jawa Barat 45464, Indonesia'),
  ('SMKN 1 Padaherang',
   'Jl. Raya Padaherang KM. 1, Karangsari, Kec. Padaherang, Kabupaten Pangandaran, Jawa Barat 46384, Indonesia'),
  ('SMKN 1 Rajadesa',
   'Jl. Kubang Atas No. 5, Sirnabaya, Kec. Rajadesa, Kabupaten Ciamis, Jawa Barat 46254, Indonesia'),
  ('SMKN 1 Rancah',
   'Jl. Rajadesa - Rancah No. 412, Cileungsir, Kec. Rancah, Kabupaten Ciamis, Jawa Barat 46387, Indonesia'),
  ('SMKN 1 Sukra',
   'Jl. Raya Pantura Sumuradem Timur, Sumuradem Timur, Kec. Sukra, Kabupaten Indramayu, Jawa Barat 45257, Indonesia'),
  ('SMKN 1 Terisi',
   'Jl. PU Cibereng-Kendayakan, Cibereng, Kec. Terisi, Kabupaten Indramayu, Jawa Barat 45262, Indonesia'),
  ('SMKN 1 Widasari',
   'Jl. By Pass Ujungjaya, Ujungjaya, Kec. Widasari, Kabupaten Indramayu, Jawa Barat 45271, Indonesia'),
  ('SMKN 2 Banjar',
   'Jl. Raya Banjar-Ciamis, Purwaharja, Kec. Purwaharja, Kota Banjar, Jawa Barat 46334, Indonesia'),
  ('SMKN 2 Ciamis',
   'Jl. Sadananya No. 21, Maleber, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46214, Indonesia'),
  ('SMKN 2 Indramayu',
   'Jl. Pabean Udik No. 15, Pabeanudik, Kec. Indramayu, Kabupaten Indramayu, Jawa Barat 45219, Indonesia'),
  ('SMKN 2 Kuningan',
   'Jl. Sukamulya No. 77, Sukamulya, Kec. Cigugur, Kabupaten Kuningan, Jawa Barat 45552, Indonesia'),
  ('SMKN 3 Banjar',
   'Jl. Julaeni, Langensari, Kec. Langensari, Kota Banjar, Jawa Barat 46341, Indonesia'),
  ('SMKN 3 Kuningan',
   'Jl. Raya Cirendang-Cigugur, Cirendang, Kec. Kuningan, Kabupaten Kuningan, Jawa Barat 45518, Indonesia'),
  ('SMKN 3 Tasikmalaya',
   'Jl. Tamansari Gobras No. 100, Mulyasari, Kec. Tamansari, Kota Tasikmalaya, Jawa Barat 46196, Indonesia'),
  ('SMKN Manonjaya',
   'Jl. Gunungtanjung KM 2,5, Margahayu, Kec. Manonjaya, Kabupaten Tasikmalaya, Jawa Barat 46197, Indonesia'),
  ('SMP Al Irsyad Al Islamiyyah Purwokerto',
   'Jl. Prof. Dr. Soeharso, Arcawinangun, Kec. Purwokerto Timur, Kabupaten Banyumas, Jawa Tengah 53113, Indonesia'),
  ('SMP BP Plus Ma''arif NU Ciamis',
   'Jl. Citapen No. 04, Sukamaju, Kec. Baregbeg, Kabupaten Ciamis, Jawa Barat 46274, Indonesia'),
  ('SMP IT Al Fawaz',
   'Jl. Peta No. 58, Balokang, Kec. Banjar, Kota Banjar, Jawa Barat 46312, Indonesia'),
  ('SMP IT Nurul Huda Margajaya',
   'Dusun Sukasari RT 026 RW 011, Margajaya, Kec. Pamarican, Kabupaten Ciamis, Jawa Barat, Indonesia'),
  ('SMP Islam Ainurrafiq',
   'Jl. Pemuda No. 001, Panawuan, Kec. Cigandamekar, Kabupaten Kuningan, Jawa Barat 45556, Indonesia'),
  ('SMP Islam Bahrul Ulum',
   'Jl. Gunung Balong, Gunungsari, Kec. Sukaratu, Kabupaten Tasikmalaya, Jawa Barat 46415, Indonesia'),
  ('SMP Islam Terpadu Nurul Huda Kedungjajang',
   'Dusun Kebonan RT 02 RW 12, Krasak, Kec. Kedungjajang, Kabupaten Lumajang, Jawa Timur 67358, Indonesia'),
  ('SMP PUI Kawalu',
   'Jl. Saguling Panjang RT 01 RW 04, Cilamajang, Kec. Kawalu, Kota Tasikmalaya, Jawa Barat 46143, Indonesia'),
  ('SMP SMA Islam Al-Ishlah bs',
   'Jl. Raya Sudimampir Balongan, Sudimampir, Kec. Balongan, Kabupaten Indramayu, Jawa Barat 45285, Indonesia'),
  ('SMP Terpadu Al Hasan Ciamis',
   'Jl. Jenderal Ahmad Yani No. 120, Kertasari, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46213, Indonesia'),
  ('SMP Terpadu Ar-Risalah',
   'Jl. Raya Banjar KM 3,5, Pamalayan, Kec. Cijeungjing, Kabupaten Ciamis, Jawa Barat 46271, Indonesia'),
  ('SMP Terpadu Dampasan',
   'Dusun Tuban RT 02 RW 06, Ratawangi, Kec. Banjarsari, Kabupaten Ciamis, Jawa Barat, Indonesia'),
  ('SMP Terpadu Riyadlul Ulum Waddawah',
   'Komplek Pesantren Condong RT 01 RW 04, Setianegara, Kec. Cibeureum, Kota Tasikmalaya, Jawa Barat 46196, Indonesia'),
  ('SMPN 1 Banjar',
   'Jl. BKR No. 1, Hegarsari, Kec. Pataruman, Kota Banjar, Jawa Barat 46322, Indonesia'),
  ('SMPN 1 Banjarsari',
   'Jl. Pasirjengkol No. 132, Cibadak, Kec. Banjarsari, Kabupaten Ciamis, Jawa Barat 46383, Indonesia'),
  ('SMPN 1 Baregbeg',
   'Jl. Raya Desa Baregbeg No. 209, Baregbeg, Kec. Baregbeg, Kabupaten Ciamis, Jawa Barat 46274, Indonesia'),
  ('SMPN 1 Ciamis',
   'Jl. Jenderal Sudirman No. 6, Ciamis, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46211, Indonesia'),
  ('SMPN 1 Cijeungjing',
   'Jl. Ciamis-Banjar, Cijeungjing, Kec. Cijeungjing, Kabupaten Ciamis, Jawa Barat 46271, Indonesia'),
  ('SMPN 1 Cikoneng',
   'Jl. Raya Margaluyu No. 9, Margaluyu, Kec. Cikoneng, Kabupaten Ciamis, Jawa Barat 46261, Indonesia'),
  ('SMPN 1 Cimaragas',
   'Jl. Raya Cimaragas No. 262, Cimaragas, Kec. Cimaragas, Kabupaten Ciamis, Jawa Barat 46381, Indonesia'),
  ('SMPN 1 Cipaku',
   'Jl. Kawali-Buniseuri, Buniseuri, Kec. Cipaku, Kabupaten Ciamis, Jawa Barat 46252, Indonesia'),
  ('SMPN 1 Cisaga',
   'Jl. Rancah No. 16, Cisaga, Kec. Cisaga, Kabupaten Ciamis, Jawa Barat 46386, Indonesia'),
  ('SMPN 1 Karangpawitan Garut',
   'Jl. Raya Cimurah, Cimurah, Kec. Karangpawitan, Kabupaten Garut, Jawa Barat 44182, Indonesia'),
  ('SMPN 1 Lelea',
   'Jl. Raya Lelea No. 3, Lelea, Kec. Lelea, Kabupaten Indramayu, Jawa Barat 45261, Indonesia'),
  ('SMPN 1 Lumbung',
   'Jl. Kawali-Panjalu No. 1, Lumbungsari, Kec. Lumbung, Kabupaten Ciamis, Jawa Barat 46258, Indonesia'),
  ('SMPN 1 Padaherang',
   'Jl. Si Kabayan, Karangpawitan, Kec. Padaherang, Kabupaten Pangandaran, Jawa Barat 46384, Indonesia'),
  ('SMPN 1 Purwadadi',
   'Jl. Sukamulya Karangpaningal, Karangpaningal, Kec. Purwadadi, Kabupaten Ciamis, Jawa Barat 46385, Indonesia'),
  ('SMPN 1 Rajadesa',
   'Jl. Raya Timur No. 127, Rajadesa, Kec. Rajadesa, Kabupaten Ciamis, Jawa Barat 46254, Indonesia'),
  ('SMPN 1 Sukamantri',
   'Jl. Raya Barat No. 218, Cibeureum, Kec. Sukamantri, Kabupaten Ciamis, Jawa Barat 46264, Indonesia'),
  ('SMPN 2 Banjar',
   'Jl. BKR No. 16, Hegarsari, Kec. Pataruman, Kota Banjar, Jawa Barat 46322, Indonesia'),
  ('SMPN 2 Baregbeg',
   'Jl. Raya Desa Sukamulya, Sukamulya, Kec. Baregbeg, Kabupaten Ciamis, Jawa Barat 46274, Indonesia'),
  ('SMPN 2 Ciamis',
   'Jl. Jenderal Sudirman No. 241, Sindangrasa, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46215, Indonesia'),
  ('SMPN 2 Cijeungjing',
   'Jl. Karanganyar - Kadugede, Karanganyar, Kec. Cijeungjing, Kabupaten Ciamis, Jawa Barat 46271, Indonesia'),
  ('SMPN 2 Cilacap',
   'Jl. D.I. Panjaitan No. 37, Donan, Kec. Cilacap Tengah, Kabupaten Cilacap, Jawa Tengah 53222, Indonesia'),
  ('SMPN 2 Cipaku',
   'Jl. Desa Cipaku No. 5, Cipaku, Kec. Cipaku, Kabupaten Ciamis, Jawa Barat 46252, Indonesia'),
  ('SMPN 2 Garut',
   'Jl. A. Yani No. 43, Pakuwon, Kec. Garut Kota, Kabupaten Garut, Jawa Barat 44117, Indonesia'),
  ('SMPN 2 Panawangan',
   'Jl. Nagarajati No. 05, Nagarajaya, Kec. Panawangan, Kabupaten Ciamis, Jawa Barat 46255, Indonesia'),
  ('SMPN 2 Sukadana',
   'Jl. Desa Bunter, Bunter, Kec. Sukadana, Kabupaten Ciamis, Jawa Barat 46272, Indonesia'),
  ('SMPN 3 Ciamis',
   'Jl. Jenderal Sudirman No. 233, Sindangrasa, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46215, Indonesia'),
  ('SMPN 3 Rajadesa',
   'Dusun Cileueur RT 002 RW 001, Tanjungsukur, Kec. Rajadesa, Kabupaten Ciamis, Jawa Barat 46254, Indonesia'),
  ('SMPN 5 Banjar',
   'Jl. KH. Mustofa No. 557, Banjar, Kec. Banjar, Kota Banjar, Jawa Barat 46311, Indonesia'),
  ('SMPN 6 Banjarsari',
   'Jl. Cikupa No. 1, Cikupa, Kec. Banjaranyar, Kabupaten Ciamis, Jawa Barat 46384, Indonesia'),
  ('SMPN 6 Ciamis',
   'Jl. Jendral Sudirman No. 189, Sindangrasa, Kec. Ciamis, Kabupaten Ciamis, Jawa Barat 46215, Indonesia'),
  ('SMPN 7 Banjar',
   'Jl. Siliwangi No. 181, Raharja, Kec. Purwaharja, Kota Banjar, Jawa Barat 46333, Indonesia')
;

do $$
declare v_sebelum int; v_sesudah int;
begin
  select count(*) into v_sebelum from sekolah;

  insert into sekolah (name, address)
  select k.nama, k.alamat from sekolah_kurasi k
  on conflict (kunci_sekolah(name)) do update
    set name = excluded.name, address = excluded.address;

  select count(*) into v_sesudah from sekolah;
  raise notice '0063: % sekolah -> % (% baru, % diperbarui).',
    v_sebelum, v_sesudah, v_sesudah - v_sebelum,
    (select count(*) from sekolah_kurasi) - (v_sesudah - v_sebelum);
end $$;

drop table sekolah_kurasi;

do $$
declare v_s int; v_d int; v_tanpa int;
begin
  select count(*) into v_s from sekolah;
  select count(*) into v_d from (
    select 1 from sekolah group by kunci_sekolah(name) having count(*) > 1) x;
  select count(*) into v_tanpa from sekolah where address not like '%, Indonesia';
  raise notice '0063: % sekolah, % nama kembar, % alamat di luar bentuk baku.',
    v_s, v_d, v_tanpa;
  assert v_d = 0, 'masih ada nama sekolah kembar';
end $$;
